---


# Setup for arena
arena: "NoDeBuff FFA"
nameserver: "§l§cNoDeBuff"

# Armor for players
leggings: 312
boots: 313
helmet: 310
chestplate: 311

# Items for players
items: 
    - ['276', '0', '1']   
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']
    - ['438', '22', '1']

...
